[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
whitelist_transfer_hook_q2 = "GUwN4GZEyQ9dgZwJNt2c8iy2e9hYCUh6p6hHXJhpZwdJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
